AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM config for Tweeter server

#
# Global Lambda function properties. These apply to every Lambda function.
#
Globals:
  Function:
    Runtime: nodejs20.x
    CodeUri: ./dist/
    Layers:
      - !Ref tweeterLayer
    Timeout: 30
    MemorySize: 128

#
# Reusable blocks of configuration. These are referenced throughout the template to avoid duplication.
# &identifier is used to define a reusable block, and *identifier is used to reference it.
#
Metadata:
  x-common-policies: &commonPolicies
    - AWSLambdaBasicExecutionRole
    - AmazonSESFullAccess
    - CloudWatchFullAccess
    - AmazonDynamoDBFullAccess
    - AmazonS3FullAccess
    - AmazonSQSFullAccess

  x-common-cors-headers: &commonCorsHeaders
    method.response.header.Access-Control-Allow-Origin: "'*'"

  x-common-swagger-response-headers: &commonSwaggerResponseHeaders
    Access-Control-Allow-Origin:
      type: string

#
# AWS resource definitions
#
Resources:
  #
  # Web API
  #
  tweeterApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: tweeterApi
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "Tweeter API"
          version: "1.0"
        x-common-consumes: &commonConsumes
          - application/json
        x-common-produces: &commonProduces
          - application/json
        x-common-request-templates: &commonRequestTemplates
          application/json: $input.json('$')
        x-common-amazon-responses: &commonAmazonResponses
          default:
            statusCode: 200
            responseParameters: *commonCorsHeaders
          ".*bad-request.*":
            statusCode: 400
            responseParameters: *commonCorsHeaders
            responseTemplates:
              application/json: '{ "error": "$input.path(''$.errorMessage'')" }'
          ".*unauthorized.*":
            statusCode: 401
            responseParameters: *commonCorsHeaders
            responseTemplates:
              application/json: '{ "error": "$input.path(''$.errorMessage'')" }'
          ".*internal-server-error.*":
            statusCode: 500
            responseParameters: *commonCorsHeaders
            responseTemplates:
              application/json: '{ "error": "$input.path(''$.errorMessage'')" }'
        x-common-swagger-responses: &commonSwaggerResponses
          "200":
            description: "OK"
            headers: *commonSwaggerResponseHeaders
          "400":
            description: "Bad Request"
            headers: *commonSwaggerResponseHeaders
          "401":
            description: "Unauthorized"
            headers: *commonSwaggerResponseHeaders
          "500":
            description: "Internal Server Error"
            headers: *commonSwaggerResponseHeaders
        paths:
          #
          # Endpoint definitions
          #
          /user/get:
            post:
              description: "Returns a user"
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${userGetFunction.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses
          /user/create:
            post:
              description: "Creates a user"
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  ##### Change "userCreateFunction" to the actual function name.
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${userCreateFunction.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /user/login:
            post:
              description: "Logs in a user"
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${userLoginFunction.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /user/logout:
            post:
              description: "Logs a user out"
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${userLogoutFunction.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /follow/isfollower:
            post:
              description: "Returns if the given user is a follower of the other user."
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getIsFollowerStatusFunction.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /followee/count:
            post:
              description: "Returns the count of followees for a given user."
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getFolloweeCountFunction.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /followee/list:
            post:
              description: "Returns a paginated list of followees for a given user."
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  ##### Change "userCreateFunction" to the actual function name.
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getFolloweesFunction.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /follower/list:
            post:
              description: "Returns a paginated list of followers for a given user."
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getFollowersFunction.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /feed/list:
            post:
              description: "Returns a paginated list of feed items for a given user."
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getFeedFunction.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /story/list:
            post:
              description: "Returns a paginated list of story items for a given user."
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${getStoryFunction.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /status/post:
            post:
              description: "Posts a status for a user."
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${postStatusFunction.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses
            
            #
            # ADD MORE ENDPOINT DEFINITIONS HERE
            #

  #
  # SQS Queues
  #
  
  #   MyQueue:
  #     Type: AWS::SQS::Queue
  #     Properties:
  #       QueueName: MyQueue

  #
  # Lambda Layer (reused by all Lambda functions)
  #
  tweeterLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: tweeterLayer
      Description: dependencies layer for Tweeter server
      ContentUri: ./layer/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: DELETE

  #
  # Web API Lambda functions
  #
  userGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: userGetFunction
      Handler: handlers/users/GetUserHandler.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user/get
            Method: POST

  userCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: userCreateFunction
      Handler: handlers/users/CreateUserHandler.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user/create
            Method: POST

  userLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: userLoginFunction
      Handler: handlers/users/LoginUserHandler.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user/login
            Method: POST

  userLogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: userLogoutFunction
      Handler: handlers/users/LogoutUserHandler.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user/logout
            Method: POST

  getIsFollowerStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getIsFollowerStatusFunction
      Handler: handlers/follow/GetIsFollowerStatusHandler.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /follow/isfollower
            Method: POST

  getFolloweeCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getFolloweeCountFunction
      Handler: handlers/follow/GetFolloweeCountHandler.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /followee/count
            Method: POST

  getFolloweesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getFolloweesFunction
      Handler: handlers/follow/GetFolloweesHandler.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /followee/list
            Method: POST

  getFollowersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getFollowersFunction
      Handler: handlers/follow/GetFollowersHandler.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /follower/list
            Method: POST

  getFeedFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getFeedFunction
      Handler: handlers/status/GetFeedHandler.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /feed/list
            Method: POST

  getStoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getStoryFunction
      Handler: handlers/status/GetStoryHandler.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /story/list
            Method: POST

  postStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: postStatusFunction
      Handler: handlers/status/PostStatusHandler.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /status/post
            Method: POST


  #
  # ADD MORE WEB API LAMBDA DEFINITIONS HERE
  #

  #
  # SQS Queue Lambda Functions
  #

  #   MyQueueFunction:
  #     Type: AWS::Serverless::Function
  #     Properties:
  #       FunctionName: MyQueueFunction
  #       Handler: <PATH TO LAMBDA HANDLER>
  #       Policies: *commonPolicies
  #       Events:
  #         SQSTrigger:
  #           Type: SQS
  #           Properties:
  #             Queue: !GetAtt MyQueue.Arn
  #             Enabled: true

  #
  # DynamoDB Tables
  #
  followTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: follow
      AttributeDefinitions:
        - AttributeName: follower_alias
          AttributeType: S
        - AttributeName: followee_alias
          AttributeType: S
      KeySchema:
        - AttributeName: follower_alias
          KeyType: HASH
        - AttributeName: followee_alias
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: follow_index
          KeySchema:
            - AttributeName: followee_alias
              KeyType: HASH
            - AttributeName: follower_alias
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  #
  # ADD MORE TABLE DEFINITIONS HERE
  #
  